In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,10,size=(3,3))
print(arr)
                    

[[1 9 5]
 [2 8 5]
 [2 8 1]]


In [3]:
vals,vect = np.linalg.eig(arr)

In [8]:
print("Eigen values : ",vals)
print("Eigen vectors : ",vect)

Eigen values :  [13.88152731 -1.         -2.88152731]
Eigen vectors :  [[-0.61985784 -0.96107446 -0.3402591 ]
 [-0.61985784  0.26211122 -0.3402591 ]
 [-0.48119903 -0.08737041  0.87661137]]


In [14]:
#vals.tofile('values_&_vectors.csv',sep=',')

In [ ]:
#np.savetxt('values_&_vectors.csv', np.column_stack((vals,vect)) ,delimiter=',',header='values,vectors', fmt='%.d,%.2f')

In [19]:
np.savetxt('values_&_vectors.csv', np.column_stack((vals,vect)) ,delimiter=',',header='values,vectors')